"use strict";
// Tipos compartilhados entre frontend e backend
Object.defineProperty(exports, "__esModule", { value: true });
exports.TEMPOS_CARGO = exports.NIVEIS_IDIOMA = exports.NIVEIS_ESCOLARIDADE = exports.TIPOS_DADO_PROFISSIONAL = exports.NIVEIS_ESCOLARIDADE_OPORTUNIDADE = exports.OPCOES_BINARIAS_OPORTUNIDADE = exports.OPCOES_GENERO_OPORTUNIDADE = exports.FLUENCIA_PORTUGUES = exports.GENEROS = exports.OBJETIVOS_IMIGRANTE = exports.NACIONALIDADES = exports.USER_CATEGORIES = void 0;
// ✨ NOVO: Constantes para categorias de usuário
exports.USER_CATEGORIES = {
    IMIGRANTE: 'IMIGRANTE',
    EMPRESA: 'EMPRESA',
    MUNICIPIO: 'MUNICIPIO',
    ACADEMIA: 'ACADEMIA',
    FAMILIA_ACOLHIMENTO: 'FAMILIA_ACOLHIMENTO',
    ADMIN: 'ADMIN' // ✨ NOVA CATEGORIA - Interface Administração
};
// ✨ NOVO: Lista de nacionalidades no feminino - Países lusófonos primeiro, depois alfabética
exports.NACIONALIDADES = [
    // Países de língua portuguesa (prioritários)
    'Portuguesa',
    'Angolana',
    'Brasileira',
    'Cabo-verdiana',
    'Guineense',
    'Macaense',
    'Moçambicana',
    'São-tomense',
    'Timorense',
    // Outras nacionalidades (ordem alfabética)
    'Afegã',
    'Africana',
    'Albanesa',
    'Alemã',
    'Americana',
    'Andorrana',
    'Argelina',
    'Argentina',
    'Arménia',
    'Australiana',
    'Austríaca',
    'Azerbaijana',
    'Bahraini',
    'Bangladeshiana',
    'Barbadiana',
    'Belga',
    'Belizenha',
    'Bielorrussa',
    'Boliviana',
    'Bósnia',
    'Botswanesa',
    'Búlgara',
    'Burkinabe',
    'Burundesa',
    'Butanesa',
    'Cambojana',
    'Camaronesa',
    'Canadiana',
    'Catariana',
    'Cazaque',
    'Chadiana',
    'Chilena',
    'Chinesa',
    'Cipriota',
    'Colombiana',
    'Comorense',
    'Congolesa',
    'Coreana',
    'Costa-riquenha',
    'Croata',
    'Cubana',
    'Dinamarquesa',
    'Dominicana',
    'Egípcia',
    'Salvadorenha',
    'Emiradense',
    'Equatoriana',
    'Eritreia',
    'Eslovaca',
    'Eslovena',
    'Espanhola',
    'Estónia',
    'Etíope',
    'Fijiana',
    'Filipina',
    'Finlandesa',
    'Francesa',
    'Gabonesa',
    'Gambiana',
    'Ganesa',
    'Georgiana',
    'Grega',
    'Grenada',
    'Guatemalteca',
    'Guianense',
    'Haitiana',
    'Hondurenha',
    'Húngara',
    'Iemenita',
    'Indiana',
    'Indonésia',
    'Iraniana',
    'Iraquiana',
    'Irlandesa',
    'Islandesa',
    'Israelita',
    'Italiana',
    'Jamaicana',
    'Japonesa',
    'Jordana',
    'Quilombola',
    'Kosovar',
    'Kuwaitiana',
    'Laociana',
    'Letã',
    'Libanesa',
    'Liberiana',
    'Líbia',
    'Liechtensteiniana',
    'Lituana',
    'Luxemburguesa',
    'Macedónia',
    'Malgaxe',
    'Malaia',
    'Malauiana',
    'Maldivense',
    'Maliana',
    'Maltesa',
    'Marroquina',
    'Mauriciana',
    'Mauritana',
    'Mexicana',
    'Moldava',
    'Monegasca',
    'Mongol',
    'Montenegrina',
    'Namibiana',
    'Nepalesa',
    'Nicaraguense',
    'Nigeriana',
    'Nigerina',
    'Norueguesa',
    'Neozelandesa',
    'Omanense',
    'Holandesa',
    'Paquistanesa',
    'Palauense',
    'Palestiniana',
    'Panamenha',
    'Papua',
    'Paraguaia',
    'Peruana',
    'Polaca',
    'Romena',
    'Ruandesa',
    'Russa',
    'Samoana',
    'Saudita',
    'Senegalesa',
    'Serra-leonesa',
    'Sérvia',
    'Seichelense',
    'Singapurense',
    'Síria',
    'Somali',
    'Sri-lankesa',
    'Sueca',
    'Suíça',
    'Surinamesa',
    'Tailandesa',
    'Tanzaniana',
    'Tcheca',
    'Togolesa',
    'Tonganesa',
    'Tunisiana',
    'Turca',
    'Turcomena',
    'Tuvaluana',
    'Ucraniana',
    'Ugandesa',
    'Uruguaia',
    'Uzbeque',
    'Venezuelana',
    'Vietnamita',
    'Zambiana',
    'Zimbabuense',
    'Outra'
];
// ✨ NOVO: Objetivos disponíveis para imigrantes
exports.OBJETIVOS_IMIGRANTE = [
    'Emprego',
    'Formação',
    'Regularização'
];
// ✨ NOVOS ENUMS: Campos adicionais para imigrantes
exports.GENEROS = [
    'F',
    'M',
    'Outro'
];
exports.FLUENCIA_PORTUGUES = [
    'Básica',
    'Intermediária',
    'Avançada',
    'Fluente'
];
// ✨ OPORTUNIDADES DE TRABALHO: Tipos para oportunidades de empresas
exports.OPCOES_GENERO_OPORTUNIDADE = [
    'F',
    'M',
    'INDIFERENTE'
];
exports.OPCOES_BINARIAS_OPORTUNIDADE = [
    'S',
    'N',
    'INDIFERENTE'
];
exports.NIVEIS_ESCOLARIDADE_OPORTUNIDADE = [
    'Ensino Básico',
    'Ensino Secundário',
    'Ensino Profissional',
    'Licenciatura',
    'Mestrado',
    'Doutoramento',
    'Indiferente'
];
// ✨ DADOS PROFISSIONAIS: Tipos para dados estruturados de imigrantes
exports.TIPOS_DADO_PROFISSIONAL = [
    'experiencia',
    'formacao',
    'idioma'
];
exports.NIVEIS_ESCOLARIDADE = [
    'Ensino Básico',
    'Ensino Secundário',
    'Ensino Profissional',
    'Licenciatura',
    'Mestrado',
    'Doutoramento',
    'Outro'
];
exports.NIVEIS_IDIOMA = [
    'Básico',
    'Intermédio',
    'Avançado'
];
exports.TEMPOS_CARGO = [
    'Menos de 6 meses',
    '6 meses a 1 ano',
    '1 a 2 anos',
    '2 a 5 anos',
    'Mais de 5 anos'
];
